/**
 * Auto-generated by scripts/fetch-gallery.mjs — do not edit by hand.
 * Real, freely-licensed photos downloaded from Wikimedia Commons for each
 * trek's detail-page gallery. Each array maps to files in public/images/gallery/.
 */
export const trekGalleries: Record<string, string[]> = {
    "everest-base-camp": ["/images/gallery/everest-base-camp-1.jpg", "/images/gallery/everest-base-camp-2.jpg", "/images/gallery/everest-base-camp-3.jpg", "/images/gallery/everest-base-camp-4.jpg", "/images/gallery/everest-base-camp-5.jpg"],
    "everest-three-passes": ["/images/gallery/everest-three-passes-1.jpg", "/images/gallery/everest-three-passes-2.jpg", "/images/gallery/everest-three-passes-3.jpg", "/images/gallery/everest-three-passes-4.jpg", "/images/gallery/everest-three-passes-5.jpg"],
    "gokyo-lakes": ["/images/gallery/gokyo-lakes-1.jpg", "/images/gallery/gokyo-lakes-2.jpg", "/images/gallery/gokyo-lakes-3.jpg", "/images/gallery/gokyo-lakes-4.jpg", "/images/gallery/gokyo-lakes-5.jpg"],
    "everest-panorama": ["/images/gallery/everest-panorama-1.jpg", "/images/gallery/everest-panorama-2.jpg", "/images/gallery/everest-panorama-3.jpg", "/images/gallery/everest-panorama-4.jpg", "/images/gallery/everest-panorama-5.jpg"],
    "pikey-peak": ["/images/gallery/pikey-peak-1.jpg", "/images/gallery/pikey-peak-2.jpg", "/images/gallery/pikey-peak-3.jpg", "/images/gallery/pikey-peak-4.jpg", "/images/gallery/pikey-peak-5.jpg"],
    "annapurna-base-camp": ["/images/gallery/annapurna-base-camp-1.jpg", "/images/gallery/annapurna-base-camp-2.jpg", "/images/gallery/annapurna-base-camp-3.jpg", "/images/gallery/annapurna-base-camp-4.jpg", "/images/gallery/annapurna-base-camp-5.jpg"],
    "annapurna-circuit": ["/images/gallery/annapurna-circuit-1.jpg", "/images/gallery/annapurna-circuit-2.jpg", "/images/gallery/annapurna-circuit-3.jpg", "/images/gallery/annapurna-circuit-4.jpg", "/images/gallery/annapurna-circuit-5.jpg"],
    "poon-hill": ["/images/gallery/poon-hill-1.jpg", "/images/gallery/poon-hill-2.png", "/images/gallery/poon-hill-3.jpg", "/images/gallery/poon-hill-4.jpg", "/images/gallery/poon-hill-5.jpg"],
    "tilicho-lake": ["/images/gallery/tilicho-lake-1.jpg", "/images/gallery/tilicho-lake-2.jpg", "/images/gallery/tilicho-lake-3.jpg", "/images/gallery/tilicho-lake-4.jpg", "/images/gallery/tilicho-lake-5.jpg"],
    "machapuchare-base-camp": ["/images/gallery/machapuchare-base-camp-1.jpg", "/images/gallery/machapuchare-base-camp-2.jpg", "/images/gallery/machapuchare-base-camp-3.jpg", "/images/gallery/machapuchare-base-camp-4.jpg", "/images/gallery/machapuchare-base-camp-5.jpg"],
    "royal-trek": ["/images/gallery/royal-trek-1.jpg", "/images/gallery/royal-trek-2.jpg", "/images/gallery/royal-trek-3.jpg", "/images/gallery/royal-trek-4.jpg", "/images/gallery/royal-trek-5.jpg"],
    "mardi-himal": ["/images/gallery/mardi-himal-1.jpg", "/images/gallery/mardi-himal-2.jpg", "/images/gallery/mardi-himal-3.jpg", "/images/gallery/mardi-himal-4.jpg", "/images/gallery/mardi-himal-5.jpg"],
    "manaslu-circuit": ["/images/gallery/manaslu-circuit-1.jpg", "/images/gallery/manaslu-circuit-2.jpg", "/images/gallery/manaslu-circuit-3.jpg", "/images/gallery/manaslu-circuit-4.jpg", "/images/gallery/manaslu-circuit-5.jpg"],
    "tsum-valley": ["/images/gallery/tsum-valley-1.jpg", "/images/gallery/tsum-valley-2.jpg", "/images/gallery/tsum-valley-3.jpg", "/images/gallery/tsum-valley-4.jpg", "/images/gallery/tsum-valley-5.jpg"],
    "nar-phu-valley": [],
    "langtang-valley": ["/images/gallery/langtang-valley-1.jpg", "/images/gallery/langtang-valley-2.jpg", "/images/gallery/langtang-valley-3.jpg", "/images/gallery/langtang-valley-4.jpg", "/images/gallery/langtang-valley-5.jpg"],
    "langtang-gosaikunda": ["/images/gallery/langtang-gosaikunda-1.jpg", "/images/gallery/langtang-gosaikunda-2.jpg", "/images/gallery/langtang-gosaikunda-3.jpg", "/images/gallery/langtang-gosaikunda-4.jpg", "/images/gallery/langtang-gosaikunda-5.jpg"],
    "helambu": ["/images/gallery/helambu-1.jpg", "/images/gallery/helambu-2.jpg", "/images/gallery/helambu-3.jpg", "/images/gallery/helambu-4.jpg", "/images/gallery/helambu-5.jpg"],
    "tamang-heritage": ["/images/gallery/tamang-heritage-1.jpg", "/images/gallery/tamang-heritage-2.jpg", "/images/gallery/tamang-heritage-3.jpg", "/images/gallery/tamang-heritage-4.jpg"],
    "upper-mustang": ["/images/gallery/upper-mustang-1.jpg", "/images/gallery/upper-mustang-2.jpg", "/images/gallery/upper-mustang-3.jpg", "/images/gallery/upper-mustang-4.jpg", "/images/gallery/upper-mustang-5.jpg"],
    "lower-mustang": ["/images/gallery/lower-mustang-1.jpg", "/images/gallery/lower-mustang-2.jpg", "/images/gallery/lower-mustang-3.jpg", "/images/gallery/lower-mustang-4.jpg", "/images/gallery/lower-mustang-5.jpg"],
    "upper-dolpo": ["/images/gallery/upper-dolpo-1.jpg", "/images/gallery/upper-dolpo-2.jpg", "/images/gallery/upper-dolpo-3.jpg", "/images/gallery/upper-dolpo-4.jpg", "/images/gallery/upper-dolpo-5.jpg"],
    "lower-dolpo": ["/images/gallery/lower-dolpo-1.jpg", "/images/gallery/lower-dolpo-2.jpg", "/images/gallery/lower-dolpo-3.jpg", "/images/gallery/lower-dolpo-4.jpg", "/images/gallery/lower-dolpo-5.jpg"],
    "makalu-base-camp": ["/images/gallery/makalu-base-camp-1.jpg", "/images/gallery/makalu-base-camp-2.jpg", "/images/gallery/makalu-base-camp-3.jpg", "/images/gallery/makalu-base-camp-4.jpg"],
    "dhaulagiri-circuit": ["/images/gallery/dhaulagiri-circuit-1.jpg", "/images/gallery/dhaulagiri-circuit-2.jpg", "/images/gallery/dhaulagiri-circuit-3.jpg", "/images/gallery/dhaulagiri-circuit-4.jpg", "/images/gallery/dhaulagiri-circuit-5.jpg"],
    "rara-lake": ["/images/gallery/rara-lake-1.jpg", "/images/gallery/rara-lake-2.jpg", "/images/gallery/rara-lake-3.jpg", "/images/gallery/rara-lake-4.jpg", "/images/gallery/rara-lake-5.jpg"],
    "humla-limi-valley": ["/images/gallery/humla-limi-valley-1.jpg", "/images/gallery/humla-limi-valley-2.jpg"],
    "ganesh-himal": ["/images/gallery/ganesh-himal-1.jpg", "/images/gallery/ganesh-himal-2.jpg", "/images/gallery/ganesh-himal-3.jpg", "/images/gallery/ganesh-himal-4.jpg", "/images/gallery/ganesh-himal-5.jpg"],
    "kanchenjunga-base-camp": ["/images/gallery/kanchenjunga-base-camp-1.jpg", "/images/gallery/kanchenjunga-base-camp-2.jpg", "/images/gallery/kanchenjunga-base-camp-3.jpg"],
};
